# Generated by Django 6.0.1 on 2026-01-27 17:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Секретный ключ ссылки', unique=True)),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во скачиваний')),
                ('max_usages', models.PositiveIntegerField(default=3, help_text='Сколько раз можно скачать по одной ссылке', verbose_name='Лимит скачиваний')),
                ('expires_at', models.DateTimeField(verbose_name='Срок действия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.collection')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to='orders.order')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.track')),
            ],
        ),
    ]
