# Generated by Django 6.0.1 on 2026-08-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='yookassa_payment_id',
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.CharField(choices=[('mock', 'Mock'), ('lemonsqueezy', 'Lemon Squeezy'), ('btcpay', 'BTCPay')], default='mock', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='provider_payment_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
