# Generated by Django 6.0.1 on 2026-01-27 17:00

import django.core.files.storage
import django.db.models.deletion
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(help_text='URL-адрес категории', unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тег')),
                ('slug', models.SlugField(unique=True)),
                ('tag_type', models.CharField(choices=[('usage', 'По назначению'), ('instrument', 'По инструментам'), ('mood', 'По настроению')], default='mood', max_length=20, verbose_name='Тип тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['tag_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название трека')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description_short', models.TextField(blank=True, help_text='Для превью', verbose_name='Краткое описание')),
                ('description_full', models.TextField(blank=True, verbose_name='Полное описание')),
                ('cover_image', models.ImageField(help_text='1200x630px, темная эстетика', upload_to='covers/%Y/%m/', verbose_name='Обложка')),
                ('audio_file_preview', models.FileField(help_text='Публичный файл, 60 сек, с водяным знаком или урезанный', upload_to='previews/', verbose_name='Аудиопример (MP3)')),
                ('audio_file_full', models.FileField(help_text='Файл, который получит клиент после оплаты', storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/rodion/Project/proffmusic/protected_media')), upload_to='tracks/', verbose_name='Полный файл (ZIP/WAV)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (RUB)')),
                ('is_new', models.BooleanField(default=True, help_text='Галочка для блока Новинки', verbose_name='Выводить в новинках')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='music.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(blank=True, related_name='tracks', to='music.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название сборника')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('cover_image', models.ImageField(upload_to='collections/%Y/%m/', verbose_name='Обложка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (RUB)')),
                ('is_new', models.BooleanField(default=False, verbose_name='В новинках')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracks', models.ManyToManyField(related_name='collections', to='music.track', verbose_name='Треки в сборнике')),
            ],
            options={
                'verbose_name': 'Сборник',
                'verbose_name_plural': 'Сборники',
            },
        ),
    ]
