# Generated by Django 6.0.1 on 2026-02-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='auto_generate_preview',
            field=models.BooleanField(default=False, help_text='Если стоит галочка, система возьмет полный трек и обрежет его согласно настройкам ниже.', verbose_name='Сгенерировать превью авто?'),
        ),
        migrations.AddField(
            model_name='track',
            name='preview_duration',
            field=models.PositiveIntegerField(default=30, help_text='Сколько секунд длится превью', verbose_name='Длительность (сек)'),
        ),
        migrations.AddField(
            model_name='track',
            name='preview_start_time',
            field=models.PositiveIntegerField(default=0, help_text='С какой секунды начинать обрезку', verbose_name='Начало превью (сек)'),
        ),
    ]
