# Generated by Django 6.0.1 on 2026-01-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.DurationField(blank=True, help_text='Вычисляется автоматически', null=True, verbose_name='Длительность'),
        ),
    ]
