# Generated by Django 6.0.1 on 2026-02-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_track_auto_generate_preview_track_preview_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_file_preview',
            field=models.FileField(blank=True, help_text='Публичный файл, 60 сек, с водяным знаком или урезанный', null=True, upload_to='previews/', verbose_name='Аудиопример (MP3)'),
        ),
    ]
