# Generated by Django 6.0.1 on 2026-07-31 14:37

from django.db import migrations, models


def copy_names_to_ru(apps, schema_editor):
    """Копирует значения из старых полей в новые *_ru поля."""
    Category = apps.get_model('music', 'Category')
    Tag = apps.get_model('music', 'Tag')
    Track = apps.get_model('music', 'Track')
    Collection = apps.get_model('music', 'Collection')

    for obj in Category.objects.all():
        obj.name_ru = obj.name
        obj.save(update_fields=['name_ru'])

    for obj in Tag.objects.all():
        obj.name_ru = obj.name
        obj.save(update_fields=['name_ru'])

    for obj in Track.objects.all():
        obj.title_ru = obj.title
        obj.description_short_ru = obj.description_short
        obj.description_full_ru = obj.description_full
        obj.save(update_fields=['title_ru', 'description_short_ru', 'description_full_ru'])

    for obj in Collection.objects.all():
        obj.title_ru = obj.title
        obj.description_ru = obj.description
        obj.save(update_fields=['title_ru', 'description_ru'])


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_track_audio_file_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag_type', 'name_ru'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Название (RU)'),
        ),
        migrations.AddField(
            model_name='collection',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='collection',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Описание (RU)'),
        ),
        migrations.AddField(
            model_name='collection',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название сборника (EN)'),
        ),
        migrations.AddField(
            model_name='collection',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название сборника (RU)'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Тег (EN)'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Тег (RU)'),
        ),
        migrations.AddField(
            model_name='track',
            name='description_full_en',
            field=models.TextField(blank=True, verbose_name='Полное описание (EN)'),
        ),
        migrations.AddField(
            model_name='track',
            name='description_full_ru',
            field=models.TextField(blank=True, verbose_name='Полное описание (RU)'),
        ),
        migrations.AddField(
            model_name='track',
            name='description_short_en',
            field=models.TextField(blank=True, help_text='Для превью', verbose_name='Краткое описание (EN)'),
        ),
        migrations.AddField(
            model_name='track',
            name='description_short_ru',
            field=models.TextField(blank=True, help_text='Для превью', verbose_name='Краткое описание (RU)'),
        ),
        migrations.AddField(
            model_name='track',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название трека (EN)'),
        ),
        migrations.AddField(
            model_name='track',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Название трека (RU)'),
        ),
        # Копируем существующие русские данные в новые поля
        migrations.RunPython(copy_names_to_ru, migrations.RunPython.noop),
        # И только теперь удаляем старые поля
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='title',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.RemoveField(
            model_name='track',
            name='description_full',
        ),
        migrations.RemoveField(
            model_name='track',
            name='description_short',
        ),
        migrations.RemoveField(
            model_name='track',
            name='title',
        ),
    ]