# Generated by Django 6.0.1 on 2026-08-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_tag_options_remove_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (USD)'),
        ),
        migrations.AlterField(
            model_name='track',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (USD)'),
        ),
    ]
