# Generated by Django 6.0.1 on 2026-08-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_track_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='purchases_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Куплено раз'),
        ),
    ]
